
import java.awt.HeadlessException;
import static java.awt.SystemColor.text;
import java.io.*;
import static java.lang.System.out;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.event.*;
import javax.swing.undo.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author alu20919409n
 */
public class MainFrame extends javax.swing.JFrame {

    UndoManager undoManager = new UndoManager();
    File fileToSave;
    private boolean saved = false;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jDialogNew = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        DialogNewYes = new javax.swing.JButton();
        DialogNewNo = new javax.swing.JButton();
        DialogNewCancel = new javax.swing.JButton();
        jDialogExit = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        DialogExitYes = new javax.swing.JButton();
        DialogExitNo = new javax.swing.JButton();
        DialogExitCancel = new javax.swing.JButton();
        jDialogAbout = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnSave = new javax.swing.JButton();
        btnLoad = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuItemNew = new javax.swing.JMenuItem();
        menuItemOpenFile = new javax.swing.JMenuItem();
        menuItemSave = new javax.swing.JMenuItem();
        menuItemSaveAs = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItemExit = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        menuItemUndo = new javax.swing.JMenuItem();
        menuItemRedo = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuItemAbout = new javax.swing.JMenuItem();

        jDialogNew.setMinimumSize(new java.awt.Dimension(400, 100));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Bundle"); // NOI18N
        jLabel2.setText(bundle.getString("MainFrame.jLabel2.text")); // NOI18N
        jLabel2.setToolTipText(bundle.getString("MainFrame.jLabel2.toolTipText")); // NOI18N

        DialogNewYes.setText(bundle.getString("MainFrame.DialogNewYes.text")); // NOI18N
        DialogNewYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DialogNewYesActionPerformed(evt);
            }
        });

        DialogNewNo.setText(bundle.getString("MainFrame.DialogNewNo.text")); // NOI18N
        DialogNewNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DialogNewNoActionPerformed(evt);
            }
        });

        DialogNewCancel.setText(bundle.getString("MainFrame.DialogNewCancel.text")); // NOI18N
        DialogNewCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DialogNewCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogNewLayout = new javax.swing.GroupLayout(jDialogNew.getContentPane());
        jDialogNew.getContentPane().setLayout(jDialogNewLayout);
        jDialogNewLayout.setHorizontalGroup(
            jDialogNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogNewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogNewLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jDialogNewLayout.createSequentialGroup()
                        .addComponent(DialogNewYes)
                        .addGap(18, 18, 18)
                        .addComponent(DialogNewNo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DialogNewCancel)
                        .addGap(20, 20, 20))))
        );
        jDialogNewLayout.setVerticalGroup(
            jDialogNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogNewLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addGroup(jDialogNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DialogNewYes)
                    .addComponent(DialogNewNo)
                    .addComponent(DialogNewCancel))
                .addGap(39, 39, 39))
        );

        jDialogExit.setMinimumSize(new java.awt.Dimension(400, 100));

        jLabel3.setText(bundle.getString("MainFrame.jLabel3.text")); // NOI18N
        jLabel3.setToolTipText(bundle.getString("MainFrame.jLabel3.toolTipText")); // NOI18N

        DialogExitYes.setText(bundle.getString("MainFrame.DialogExitYes.text")); // NOI18N
        DialogExitYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DialogExitYesActionPerformed(evt);
            }
        });

        DialogExitNo.setText(bundle.getString("MainFrame.DialogExitNo.text")); // NOI18N
        DialogExitNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DialogExitNoActionPerformed(evt);
            }
        });

        DialogExitCancel.setText(bundle.getString("MainFrame.DialogExitCancel.text")); // NOI18N
        DialogExitCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DialogExitCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogExitLayout = new javax.swing.GroupLayout(jDialogExit.getContentPane());
        jDialogExit.getContentPane().setLayout(jDialogExitLayout);
        jDialogExitLayout.setHorizontalGroup(
            jDialogExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogExitLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogExitLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jDialogExitLayout.createSequentialGroup()
                        .addComponent(DialogExitYes)
                        .addGap(18, 18, 18)
                        .addComponent(DialogExitNo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DialogExitCancel)
                        .addGap(20, 20, 20))))
        );
        jDialogExitLayout.setVerticalGroup(
            jDialogExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogExitLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addGroup(jDialogExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DialogExitYes)
                    .addComponent(DialogExitNo)
                    .addComponent(DialogExitCancel))
                .addGap(39, 39, 39))
        );

        jDialogAbout.setMinimumSize(new java.awt.Dimension(400, 200));

        jLabel4.setText(bundle.getString("MainFrame.jLabel4.text")); // NOI18N
        jLabel4.setToolTipText(bundle.getString("MainFrame.jLabel4.toolTipText")); // NOI18N

        btnClose.setText(bundle.getString("MainFrame.btnClose.text")); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel5.setText(bundle.getString("MainFrame.jLabel5.text")); // NOI18N

        javax.swing.GroupLayout jDialogAboutLayout = new javax.swing.GroupLayout(jDialogAbout.getContentPane());
        jDialogAbout.getContentPane().setLayout(jDialogAboutLayout);
        jDialogAboutLayout.setHorizontalGroup(
            jDialogAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogAboutLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jDialogAboutLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(btnClose)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDialogAboutLayout.setVerticalGroup(
            jDialogAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(btnClose)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 700));

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnSave.setText(bundle.getString("MainFrame.btnSave.text")); // NOI18N
        btnSave.setFocusable(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSave);

        btnLoad.setText(bundle.getString("MainFrame.btnLoad.text")); // NOI18N
        btnLoad.setFocusable(false);
        btnLoad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLoad.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLoad);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        textArea.getDocument().addUndoableEditListener(new
            UndoableEditListener() {
                @Override
                public void undoableEditHappened(UndoableEditEvent e) {
                    // TODO Auto-generated method stub
                    undoManager.addEdit(e.getEdit());
                }
            });
            textArea.setColumns(20);
            textArea.setRows(5);
            textArea.setName(""); // NOI18N
            jScrollPane1.setViewportView(textArea);

            getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

            menuFile.setText(bundle.getString("MainFrame.menuFile.text")); // NOI18N

            menuItemNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
            menuItemNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new-file-icon (1).png"))); // NOI18N
            menuItemNew.setText(bundle.getString("MainFrame.menuItemNew.text")); // NOI18N
            menuItemNew.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    menuItemNewActionPerformed(evt);
                }
            });
            menuFile.add(menuItemNew);

            menuItemOpenFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
            menuItemOpenFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Open-file-icon.png"))); // NOI18N
            menuItemOpenFile.setText(bundle.getString("MainFrame.menuItemOpenFile.text")); // NOI18N
            menuItemOpenFile.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    menuItemOpenFileActionPerformed(evt);
                }
            });
            menuFile.add(menuItemOpenFile);

            menuItemSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
            menuItemSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Save-icon.png"))); // NOI18N
            menuItemSave.setText(bundle.getString("MainFrame.menuItemSave.text")); // NOI18N
            menuItemSave.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    menuItemSaveActionPerformed(evt);
                }
            });
            menuFile.add(menuItemSave);

            menuItemSaveAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Save-as-icon.png"))); // NOI18N
            menuItemSaveAs.setText(bundle.getString("MainFrame.menuItemSaveAs.text")); // NOI18N
            menuItemSaveAs.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    menuItemSaveAsActionPerformed(evt);
                }
            });
            menuFile.add(menuItemSaveAs);
            menuFile.add(jSeparator1);

            menuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close-icon.png"))); // NOI18N
            menuItemExit.setText(bundle.getString("MainFrame.menuItemExit.text")); // NOI18N
            menuItemExit.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    menuItemExitActionPerformed(evt);
                }
            });
            menuFile.add(menuItemExit);

            jMenuBar1.add(menuFile);

            menuEdit.setText(bundle.getString("MainFrame.menuEdit.text")); // NOI18N

            menuItemUndo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
            menuItemUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Undo-icon.png"))); // NOI18N
            menuItemUndo.setText(bundle.getString("MainFrame.menuItemUndo.text")); // NOI18N
            menuItemUndo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    menuItemUndoActionPerformed(evt);
                }
            });
            menuEdit.add(menuItemUndo);

            menuItemRedo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
            menuItemRedo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Redo-icon.png"))); // NOI18N
            menuItemRedo.setText(bundle.getString("MainFrame.menuItemRedo.text")); // NOI18N
            menuItemRedo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    menuItemRedoActionPerformed(evt);
                }
            });
            menuEdit.add(menuItemRedo);

            jMenuBar1.add(menuEdit);

            menuHelp.setText(bundle.getString("MainFrame.menuHelp.text")); // NOI18N

            menuItemAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Actions-help-about-icon.png"))); // NOI18N
            menuItemAbout.setText(bundle.getString("MainFrame.menuItemAbout.text")); // NOI18N
            menuItemAbout.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    menuItemAboutActionPerformed(evt);
                }
            });
            menuHelp.add(menuItemAbout);

            jMenuBar1.add(menuHelp);

            setJMenuBar(jMenuBar1);

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void menuItemNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNewActionPerformed
        jDialogNew.setVisible(true);
    }//GEN-LAST:event_menuItemNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (saved == true) {
            save();
        } else {
            menuItemSaveAsActionPerformed(evt);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    public void save() {
        BufferedWriter out = null;
        try {
            out = new BufferedWriter(new FileWriter(fileToSave));
            out.write(textArea.getText());
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            if (out != null) {
                try {
                    out.close();
                } catch (IOException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    public void openFile() {
        saved = true;
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            fileToSave = fileChooser.getSelectedFile();
            try {
                textArea.read(new FileReader(fileToSave.getAbsolutePath()), null);
            } catch (IOException ex) {
                System.out.println("problem accessing file" + fileToSave.getAbsolutePath());
            }
        } else {
            System.out.println("File access cancelled by user.");
        }
    }

    public MainFrame(JButton btnLoad, JButton btnSave, JFileChooser fileChooser, JLabel jLabel1, JMenuBar jMenuBar1, JMenuItem jMenuItem5, JMenuItem jMenuItem6, JScrollPane jScrollPane1, JPopupMenu.Separator jSeparator1, JToolBar jToolBar1, JMenu menuAbout, JMenu menuEdit, JMenu menuFile, JMenuItem menuItemExit, JMenuItem menuItemNew, JMenuItem menuItemOpenFile, JMenuItem menuItemSave, JMenuItem menuItemSaveAs, JTextArea textArea) throws HeadlessException {
        this.btnLoad = btnLoad;
        this.btnSave = btnSave;
        this.fileChooser = fileChooser;
        this.jMenuBar1 = jMenuBar1;
        this.menuItemUndo = jMenuItem5;
        this.menuItemRedo = jMenuItem6;
        this.jScrollPane1 = jScrollPane1;
        this.jSeparator1 = jSeparator1;
        this.jToolBar1 = jToolBar1;
        this.menuHelp = menuAbout;
        this.menuEdit = menuEdit;
        this.menuFile = menuFile;
        this.menuItemExit = menuItemExit;
        this.menuItemNew = menuItemNew;
        this.menuItemOpenFile = menuItemOpenFile;
        this.menuItemSave = menuItemSave;
        this.menuItemSaveAs = menuItemSaveAs;
        this.textArea = textArea;
    }

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        openFile();
    }//GEN-LAST:event_btnLoadActionPerformed

    private void menuItemOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemOpenFileActionPerformed
        openFile();
    }//GEN-LAST:event_menuItemOpenFileActionPerformed

    private void menuItemSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSaveAsActionPerformed
        JFileChooser s = new JFileChooser();
        int returnVal = s.showSaveDialog(this);
        fileToSave = s.getSelectedFile();
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                BufferedWriter out = new BufferedWriter(new FileWriter(fileToSave));
                out.write(textArea.getText());
                out.close();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
        saved = true;
    }//GEN-LAST:event_menuItemSaveAsActionPerformed

    private void menuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSaveActionPerformed
        if (saved == true) {
            save();
        } else {
            menuItemSaveAsActionPerformed(evt);
        }    }//GEN-LAST:event_menuItemSaveActionPerformed

    private void DialogNewYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DialogNewYesActionPerformed
        if (saved == true) {
            save();
        } else {
            menuItemSaveAsActionPerformed(evt);
        }
        textArea.setText("");
        saved = false;
        jDialogNew.dispose();
    }//GEN-LAST:event_DialogNewYesActionPerformed

    private void DialogNewNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DialogNewNoActionPerformed
        textArea.setText("");
        saved = false;
        jDialogNew.dispose();    }//GEN-LAST:event_DialogNewNoActionPerformed

    private void DialogNewCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DialogNewCancelActionPerformed
        jDialogNew.dispose();    }//GEN-LAST:event_DialogNewCancelActionPerformed

    private void DialogExitYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DialogExitYesActionPerformed
        if (saved == true) {
            save();
        } else {
            menuItemSaveAsActionPerformed(evt);
        }
        jDialogNew.dispose();
        System.exit(0);
    }//GEN-LAST:event_DialogExitYesActionPerformed

    private void DialogExitNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DialogExitNoActionPerformed
        jDialogNew.dispose();
        System.exit(0);
    }//GEN-LAST:event_DialogExitNoActionPerformed

    private void DialogExitCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DialogExitCancelActionPerformed
        jDialogExit.dispose();
    }//GEN-LAST:event_DialogExitCancelActionPerformed

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        jDialogExit.setVisible(true);
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void menuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAboutActionPerformed
        jDialogAbout.setVisible(true);
    }//GEN-LAST:event_menuItemAboutActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        jDialogAbout.dispose();        jDialogAbout.dispose();        jDialogAbout.dispose();    }//GEN-LAST:event_btnCloseActionPerformed

    private void menuItemUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUndoActionPerformed
        try {
            undoManager.undo();
        } catch (CannotUndoException e) {

        }
    }//GEN-LAST:event_menuItemUndoActionPerformed

    private void menuItemRedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRedoActionPerformed
        try {
            undoManager.redo();
        } catch (CannotRedoException e) {
        }

    }//GEN-LAST:event_menuItemRedoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DialogExitCancel;
    private javax.swing.JButton DialogExitNo;
    private javax.swing.JButton DialogExitYes;
    private javax.swing.JButton DialogNewCancel;
    private javax.swing.JButton DialogNewNo;
    private javax.swing.JButton DialogNewYes;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnSave;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JDialog jDialogAbout;
    private javax.swing.JDialog jDialogExit;
    private javax.swing.JDialog jDialogNew;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuItemAbout;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemNew;
    private javax.swing.JMenuItem menuItemOpenFile;
    private javax.swing.JMenuItem menuItemRedo;
    private javax.swing.JMenuItem menuItemSave;
    private javax.swing.JMenuItem menuItemSaveAs;
    private javax.swing.JMenuItem menuItemUndo;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
